/**
 * IAU three-letter constellation abbreviations (AT-HYG `con`) → Latin genitive
 * used in Bayer–Flamsteed designations (e.g. Cet → Ceti for “Tau Ceti”).
 */
export const CON_TO_GENITIVE: Record<string, string> = {
  And: "Andromedae",
  Ant: "Antliae",
  Aps: "Apodis",
  Aqr: "Aquarii",
  Aql: "Aquilae",
  Ara: "Arae",
  Ari: "Arietis",
  Aur: "Aurigae",
  Boo: "Boötis",
  Cae: "Caeli",
  Cam: "Camelopardalis",
  Cap: "Capricorni",
  Car: "Carinae",
  Cas: "Cassiopeiae",
  Cen: "Centauri",
  Cep: "Cephei",
  Cet: "Ceti",
  Cha: "Chamaeleontis",
  Cir: "Circini",
  CMa: "Canis Majoris",
  CMi: "Canis Minoris",
  Cnc: "Cancri",
  Col: "Columbae",
  Com: "Comae Berenices",
  CrA: "Coronae Australis",
  CrB: "Coronae Borealis",
  Crt: "Crateris",
  Cru: "Crucis",
  Crv: "Corvi",
  CVn: "Canum Venaticorum",
  Cyg: "Cygni",
  Del: "Delphini",
  Dor: "Doradus",
  Dra: "Draconis",
  Equ: "Equulei",
  Eri: "Eridani",
  For: "Fornacis",
  Gem: "Geminorum",
  Gru: "Gruis",
  Her: "Herculis",
  Hor: "Horologii",
  Hya: "Hydrae",
  Hyi: "Hydri",
  Ind: "Indi",
  Lac: "Lacertae",
  Leo: "Leonis",
  LMi: "Leonis Minoris",
  Lep: "Leporis",
  Lib: "Librae",
  Lup: "Lupi",
  Lyn: "Lyncis",
  Lyr: "Lyrae",
  Men: "Mensae",
  Mic: "Microscopii",
  Mon: "Monocerotis",
  Mus: "Muscae",
  Nor: "Normae",
  Oct: "Octantis",
  Oph: "Ophiuchi",
  Ori: "Orionis",
  Pav: "Pavonis",
  Peg: "Pegasi",
  Per: "Persei",
  Phe: "Phoenicis",
  Pic: "Pictoris",
  Psc: "Piscium",
  PsA: "Piscis Austrini",
  Pup: "Puppis",
  Pyx: "Pyxidis",
  Ret: "Reticuli",
  Scl: "Sculptoris",
  Sco: "Scorpii",
  Sct: "Scuti",
  Ser: "Serpentis",
  Sex: "Sextantis",
  Sge: "Sagittae",
  Sgr: "Sagittarii",
  Tau: "Tauri",
  Tel: "Telescopii",
  Tri: "Trianguli",
  TrA: "Trianguli Australis",
  Tuc: "Tucanae",
  UMa: "Ursae Majoris",
  UMi: "Ursae Minoris",
  Vel: "Velorum",
  Vir: "Virginis",
  Vol: "Volantis",
  Vul: "Vulpeculae",
};

/** Resolve `con` from AT-HYG (case may vary) to the Latin genitive. */
export function conToGenitive(con: string): string | undefined {
  const c = con.trim();
  if (!c) return undefined;
  if (CON_TO_GENITIVE[c]) return CON_TO_GENITIVE[c];
  const found = Object.keys(CON_TO_GENITIVE).find(
    (k) => k.toLowerCase() === c.toLowerCase(),
  );
  return found ? CON_TO_GENITIVE[found] : undefined;
}
